
name: Build PassWall with OpenWrt SDK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SDK_URL: https://downloads.openwrt.org/releases/21.02.3/targets/mvebu/cortexa53/openwrt-sdk-21.02.3-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64.tar.xz
  ARTIFACT_NAME: passwall-packages
  CONFIG_FILE: config/a53.config

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup environment
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
        genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
        libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev \
        libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
        python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
        swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        
    - name: Create simulated physical disk
      run: |
        mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
        root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
        sudo truncate -s "${mnt_size}"G /mnt/mnt.img
        sudo truncate -s "${root_size}"G /root.img
        sudo losetup /dev/loop6 /mnt/mnt.img
        sudo losetup /dev/loop7 /root.img
        sudo pvcreate /dev/loop6
        sudo pvcreate /dev/loop7
        sudo vgcreate github /dev/loop6 /dev/loop7
        sudo lvcreate -n runner -l 100%FREE github
        sudo mkfs.xfs /dev/github/runner
        sudo mkdir -p /${{ env.DIY_WORK }}
        sudo mount /dev/github/runner /${{ env.DIY_WORK }}
        sudo chown $USER:$GROUPS /${{ env.DIY_WORK }}
        df -Th
    
    - name: Download OpenWrt SDK
      working-directory: /${{ env.DIY_WORK }}
      run: |
        wget ${{ env.SDK_URL }} -O sdk.tar.xz
        mkdir -p openwrt
        tar -xvJf sdk.tar.xz -C openwrt --strip-components=1
        ln -sf /${{ env.DIY_WORK }}/openwrt ${GITHUB_WORKSPACE}/openwrt
        cp -Rf ${GITHUB_WORKSPACE}/build ${GITHUB_WORKSPACE}/openwrt/build
        chmod -R +x ${GITHUB_WORKSPACE}/openwrt
        
    - name: Configure feeds
      run: |
        cd openwrt
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> feeds.conf.default
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build PassWall
      run: |
        cd openwrt
        make defconfig
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        make package/passwall/compile -j$(nproc) V=s
        
    - name: Organize files
      id: organizer
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
          mkdir -p ${{ env.DIY_WORK }}/dist/Packages
          cp -r -f ${{ env.DIY_WORK }}/openwrt/bin/packages/*/*/*.ipk ${{ env.DIY_WORK }}/dist/Packages/
          cd ${{ env.DIY_WORK }}/dist
          tar -czf a53.tar.gz Packages
          rm -rf Packages
          sha256sum `ls -1 | sort` > sha256sums
          echo "::set-output name=status::success"
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.FIRMWARE }}
